server:
  port: 5004
spring:
  application:
    name: feign-service
  datasource:
    url: jdbc:mysql://localhost:3306/onix
    username: root
    password: justdoit
    driverClassName: com.mysql.jdbc.Driver
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/